name: testes back

on: push

jobs:
  test: 
    name: API testes
    runs-on: ubuntu-latest
    
    steps:
      - name: Clonagem projeto
        uses: actions/checkout@v4

      - name: configuração do Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar Dependencias do projeto
        run: |
          pip install robotframework
          pip install robotframework-requests
          
      - name: Execução dos Testes de API    
        run: |
          robot --name "API Tests" --outputdir results/ test/

      - name: Salvando Relatorios dos Testes 📝
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: robot-framework-report
          path: results/

  deploy:
    name: Deploy GitHub Pages 🌐
    runs-on: ubuntu-latest
    needs: 
      - test
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://Renilsonsantos.github.io/TestesRobot/report.html
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v2
 
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with: 
          name: robot-framework-report
          path: results/
 
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: results/
 
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v1
