name: testes back

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clonagem projeto
        uses: actions/checkout@v3

      - name: configuração do Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Execução dos Testes de API    
        run: |
          robot -d results tests
