name: testes back

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clonagem projeto
        uses: actions/checkout@v3

      - name: configuração do Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Instalar Dependencias do projeto
        run: |
          pip install robotframework
          pip install robotframework-requests
          
      - name: Execução dos Testes de API    
        run: |
          robot --name "API Tests" --outputdir results/ test/

      - name: Salvando Relatorios dos Testes 📝
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: robot-framework-report
          path: results/
